### ISSUE TITLE
Implement first set of static views

### ISSUE THREAD

**Issue by taptrust** [taptrust/taptrust-wallet#1]
This initial step will not involve any API integration, although it may contain basic navigation logic to be able to move between views. It's fine to use placeholder values wherever information will be populated via API calls.

Reference this document: https://docs.google.com/document/d/1PEeeJ2cPVDEM1MnWxHGzVoEILMLAolR-dx6NhVK8i3E/edit

Implement:
- Splash screen
- Login screen
- Register screen
- App authorization home

Do not implement:
- App Authorization Approval
- List App Authorizations
- View App Authorization Details
- Navigation Drawer

**Comment by nevinod** [comment]
Finished all four screens, but does not do API calls

**Comment by jamslevy** [comment]
@nevinod looks good, a couple minor things:

1. Can you implement the "Create new account" and "Have an account?" links as specified on Login/Register pages in this document https://docs.google.com/document/d/1PEeeJ2cPVDEM1MnWxHGzVoEILMLAolR-dx6NhVK8i3E/edit and enable navigation between the two screens via the link? Currently I dont think there is a way to view the Register screen.

2. I keep seeing an Expo error screen - see attachment. Would be very helpful for debugging if there is a way to fix this! If you don't know how to fix this I'll try to figure it out 

[Screen Shot 2018-09-11 at 6.11.05 PM.zip](https://github.com/taptrust/taptrust-wallet/files/2373197/Screen.Shot.2018-09-11.at.6.11.05.PM.zip)
