### ISSUE TITLE
Auth approval  view should dynamically populate for transactions and sessions

### ISSUE THREAD

**Issue by jamslevy** [taptrust/taptrust-wallet#15]
The AuthApproval view currently has hard-coded values (https://github.com/taptrust/taptrust-wallet/blob/develop/src/screens/AuthApproval.js#L17-L24)

We want to adjust the implementation so it uses dynamic values provided from the API, and also renders different if the request has type "transaction" or "session". 

Specifically, the following values should be re-named and linked to the corresponding API values:

* request_id -> session.request.app.name
* ethAmount -> session.request.value
* logo_url -> session.request.app.icon-url
* hoursLeft -> session.request.duration
* app_url -> session.request.app.url

Also if session.request.type is "transaction" the approval view should be rendered like the following example:

![screen shot 2018-09-29 at 8 41 58 pm](https://user-images.githubusercontent.com/17043/46253091-475fd980-c428-11e8-8ff1-700a30b06321.png)

If session.request.type is "session" the approval view should be rendered as currently implemented ("is requesting the following permissions", "spend up to {value}", "expires in {duration} hours") and does not currently need to include the session.request.recipient address.

When this refactoring is complete, it should be possible to use the testing tool to generate a transaction or session request, and then to successfully approve it from the mobile client.  Please upload at least one example of the auth approval screen using both transaction and session requests generated from the testing tool. 

Test tool: www.taptrust.com/examples/dapp 

API documentation: https://github.com/taptrust/taptrust-wallet/wiki/API-Overview#request-object

**Comment by milosristic124** [comment]
![simulator screen shot - iphone 8 plus - 2018-10-01 at 16 49 36](https://user-images.githubusercontent.com/28895488/46296277-464eb980-c59a-11e8-98d0-28a5ec473beb.png)
![simulator screen shot - iphone 8 plus - 2018-10-01 at 16 48 37](https://user-images.githubusercontent.com/28895488/46296278-464eb980-c59a-11e8-850c-e71c72f100e7.png)

**Comment by milosristic124** [comment]
![image](https://user-images.githubusercontent.com/28895488/46297283-a21a4200-c59c-11e8-9311-474b26ac97b9.png)

**Comment by jamslevy** [comment]
Completed
