### ISSUE TITLE
Implement static Offers view 

### ISSUE THREAD

**Issue by jamslevy** [taptrust/taptrust-wallet#17]
Before "Logout" option in menu, add "Offers" menu option. Tapping this option should open a new Offers view. For now it can be a static rendering of the following:

![screen shot 2018-10-01 at 6 01 17 pm](https://user-images.githubusercontent.com/17043/46323756-b4987980-c5a4-11e8-95e8-121e80b49cf2.png)

Instead of hard-coding all the list items directly, specify a data structure to use and a for-loop, so that it will be easier to migrate to using API data. 

For specs, see https://preview.uxpin.com/b83541f013a32cd791f53334f27133ec4db0ecf1#/pages/93815168/specification/sitemap?mode=i

**Comment by milosristic124** [comment]
![simulator screen shot - iphone 8 plus - 2018-10-03 at 15 31 37](https://user-images.githubusercontent.com/28895488/46413709-d79c6800-c721-11e8-92e6-2a4c6e419070.png)
![simulator screen shot - iphone 8 plus - 2018-10-03 at 15 31 39](https://user-images.githubusercontent.com/28895488/46413710-d834fe80-c721-11e8-9c72-af23744682ea.png)
![simulator screen shot - iphone 8 plus - 2018-10-03 at 15 31 41](https://user-images.githubusercontent.com/28895488/46413711-d834fe80-c721-11e8-8dd6-d31744b19070.png)

**Comment by milosristic124** [comment]
And this the dynamic data.

const offersList = [
    {
        icon_url: 'http://www.taptrust.com/static/img/twitter@2x.png',
        name: 'Collectible dApp',
        amount: '10',
        description: 'Sponsored by dApp center',
        type: 'gaming_collectible'
    },
    {
        icon_url: 'http://www.taptrust.com/static/img/twitter@2x.png',
        name: 'Milos dApp',
        amount: '25',
        description: 'Sponsored by dApp center',
        type: 'gaming_collectible'
    },
    {
        icon_url: 'http://www.taptrust.com/static/img/twitter@2x.png',
        name: 'Wow dApp',
        amount: '40',
        description: 'Sponsored by dApp center',
        type: 'marketplaces'
    },
    {
        icon_url: 'http://www.taptrust.com/static/img/twitter@2x.png',
        name: 'Great dApp',
        amount: '99',
        description: 'Sponsored by dApp center',
        type: 'marketplaces'
    },
];
