### ISSUE TITLE
Implement static Security Alert view

### ISSUE THREAD

**Issue by jamslevy** [taptrust/taptrust-wallet#18]
Before "Logout" option in menu, add "Security" menu option. Tapping this option should open a new SecurityAlert view. For now it can be a static rendering of the following:

![screen shot 2018-10-01 at 6 01 25 pm](https://user-images.githubusercontent.com/17043/46323794-e9a4cc00-c5a4-11e8-83f3-53103bf8085f.png)

Instead of hard-coding the items directly, specify a data structure to use so that it will be easier to migrate to using API data for this view.

For specs, see https://preview.uxpin.com/b83541f013a32cd791f53334f27133ec4db0ecf1#/pages/93815169/specification/sitemap?mode=i

**Comment by milosristic124** [comment]
![simulator screen shot - iphone 8 plus - 2018-10-03 at 15 31 49](https://user-images.githubusercontent.com/28895488/46413809-103c4180-c722-11e8-8e3c-e2997e81ee88.png)

**Comment by milosristic124** [comment]
Dynamic data:

const alertData = {
    icon_url: 'http://www.taptrust.com/static/img/twitter@2x.png',
    address: '0x70928213bc4e7',
    name: 'Etheroll'
}

**Comment by milosristic124** [comment]
![simulator screen shot - iphone 8 plus - 2018-10-03 at 15 39 51](https://user-images.githubusercontent.com/28895488/46414074-a07a8680-c722-11e8-864d-e6e61257f00b.png)
