### ISSUE TITLE
REST API Client and Login/Register API implementation 

### ISSUE THREAD

**Issue by taptrust** [taptrust/taptrust-wallet#3]
Reference https://docs.google.com/document/d/1PEeeJ2cPVDEM1MnWxHGzVoEILMLAolR-dx6NhVK8i3E/edit

From login view, make POST request to www.taptrust.com/api/1/login with following params:

- username (string, use login form "username" input text)
- pubkey (string, use login form "password" input text)

From register view, make POST request to www.taptrust.com/api/1/register with following params:

- username (string, use login form "username" input text)
- pubkey (string, use login form "password" input text)

For both APIs, if response contains "error" key (see http://www.taptrust.com/api/1/login?username=test_12345&pubkey=pw12345s for example), show error message.

If 200 or 202 status response is return with no error key, save the username and pubkey (password) to local memory, and navigate to the "AuthHome" view. 

For both register and login APIs, do client-side check that:

- "username" input is greater than 4 characters. If not, show error message "Username must be at least 5 characters"
- "password" input is at least six characters and contains at least one letter, one number, and one special character. If not, show error message "Password must be at least six characters and contain at least one letter, one number, and one special character". 

Example REST API Client (it doesn't have to be this library): https://www.npmjs.com/package/react-native-rest-client

Do not implement public/private key authentication during this step. At a later time the pubkey param will actually be a public key token generated from the username, password, and additional entropy.

Please contact James if you expect this ticket to require more than 8 hours to complete.

**Comment by jamslevy** [comment]
Completed
