### ISSUE TITLE
Prototype public/private key generation 

### ISSUE THREAD

**Issue by taptrust** [taptrust/taptrust-wallet#4]
From either register or login forms, before submitting API request, first generate a seed phrase in the following form:

"taptrust-wallet-{username}-{password}"

From this seed phrase, generate an elliptic curve secp256k1 private/public keypair. A library such as this one can be used: 

https://github.com/SilentCicero/ethereumjs-accounts/#method-new

Replace "pubkey" API request parameter values with the generated public key, and save the private key to local storage. If this is implemented correctly, the same username and password should produce the same keypair information on every registration or login. 

This will be modified later to be more secure.

**Comment by jamslevy** [comment]
https://ethereum.stackexchange.com/questions/8696/how-to-generate-an-ethereum-brain-wallet-in-javascript

We need to figure out how to get web3.js working with react native.

**Comment by jamslevy** [comment]
The private to public method should convert private key 'c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3' to publicKey '3f704e8b0ee605967f55081f627306090abab3a6e1400e9345bc60c78a8bef57'

**Comment by milosristic124** [comment]
https://hackernoon.com/using-core-node-js-modules-in-react-native-apps-64acd4d07140

**Comment by milosristic124** [comment]
Finally found a solution using ethereumjs-wallet.
I customized the package that can be used in React native.

ethereumjs-wallet.js looks like this:
![image](https://user-images.githubusercontent.com/28895488/46464122-dfade380-c7c5-11e8-8e8e-10655324aa36.png)


And we can import the package like this:
const wallet=require('../libraries/EthereumLib/ethereumjs-wallet');

![image](https://user-images.githubusercontent.com/28895488/46464188-13890900-c7c6-11e8-93e3-8bfba986278e.png)

Steps:
// Get token from phase using sha256
let token= sha256('taptrust-wallet-api_overview_testing1');

// Generate wallet from ethereumjs-wallet
const w=wallet.generate(false,token);

// Get Private key
var priv=w.getPrivateKeyString();

// Get Public key
const pub=w.getPublicKeyString();

![image](https://user-images.githubusercontent.com/28895488/46464516-d5d8b000-c7c6-11e8-8f3b-fa5a97d3224b.png)


The result:

public key: 0x538b67a07a378f26d6cd29de7f15d7fbf911b176f30af53a69cd59e334b16f8b1054de74fd2e0d0b18f75e987da7c12d9025bea785ce06b353300fb990809108
private Key:
0x30d1851b1fdc3e7c55f08f36979e0461c596332c5a970aed2d6deb2932ddbac8

![image](https://user-images.githubusercontent.com/28895488/46464396-8c886080-c7c6-11e8-856a-48294f749a28.png)

**Comment by milosristic124** [comment]
0x538b67a07a378f26d6cd29de7f15d7fbf911b176f30af53a69cd59e334b16f8b1054de74fd2e0d0b18f75e987da7c12d9025bea785ce06b353300fb990809108
Login.js:47 privatekye 0x30d1851b1fdc3e7c55f08f36979e0461c596332c5a970aed2d6deb2932ddbac8

**Comment by milosristic124** [comment]
So the seed phrase instead of 'taptrust-wallet-api_overview_testing1' is 'taptrust-wallet-{username}-{password}' with those values from the Login.js or Register.js fields

**Comment by jamslevy** [comment]
Completed
