### ISSUE TITLE
Implement authorization APIs and navigation drawer

### ISSUE THREAD

**Issue by taptrust** [taptrust/taptrust-wallet#5]
Reference https://docs.google.com/document/d/1PEeeJ2cPVDEM1MnWxHGzVoEILMLAolR-dx6NhVK8i3E/edit

**Creating and Updating Sessions**

This section just describes how to go about using API methods to create and update a session. The session itself is not created from the mobile client, so it is expected to be necessary to create the session from some other API client. All API methods currently support GET requests so this is even possible from a web browser.

1.  Register account (this only needs to be done once) - http://www.taptrust.com/api/1/register?username=api_overview_testing1&pubkey=test1234
2.  Create session for existing user - http://www.taptrust.com/api/1/auth/request?username=api_overview_testing1&pubkey=test1234&app-url=test&request=test
3. Copy the "session_id" value returned by the previous API method and use it for any API method requiring a session_id: http://www.taptrust.com/api/1/auth/process?session_id=api_overview_testing1-1537206565&sig=test&action=approve

**App Authorization Home**

While on this screen and it is in focus, poll the following API every 10 seconds:

https://github.com/taptrust/taptrust-wallet/wiki/API-Overview#post-api1authget

Only send these requests while on this view, and while the app is in focus (not minimized). 
Once a pending authorization session object is returned, proceed to AuthApproval View and stop polling. 

**App Authorization Approval**

The styling of this view is being completed by @nevinod so for now this view can just have an unstyled "approve" and "reject" buttons for testing API integration. 

When “Approve” or “Reject” buttons are tapped, POST to the following API with either "approve" or "reject" as the "action" value:
https://github.com/taptrust/taptrust-wallet/wiki/API-Overview#post-api1authprocess

For now use value "signature" for the "sig" request parameter value.

- Back button is equivalent to “Reject” button
- Navigate to ListAuthorizations view after “Approve” or “Reject” (if this view is not yet available, add the view although it will be styled separately) 

**List Authorizations**

The styling of this view is being completed by @nevinod so for now this view can be unstyled just for the purposes of API testing.

Use the following API:
https://github.com/taptrust/taptrust-wallet/wiki/API-Overview#post-api1authlist

- Search function does not need to be implemented at all
- The view will have three columns for "All", "Approved" and "Expired" although for now it is fine to just list them in one column until the styling of the view is in place. 
- Tapping an authorization object should navigate to "Authorization Details" view for that authorization.

**Authorization Details**

There is no additional API request needed (the information needed for this view is found in the objects returned in the List Authorizations API). The styling of this view is being completed by @nevinod so for now this view can be unstyled just for the purposes of API testing. Right now it can just be a very simple view with "Session ID: {session.session_id}" 

**Navigation Drawer**

Should be rendered in the top left corner as shown in the following image:

https://www.dropbox.com/s/l6ve6ymxoc24b6h/list_auth.png?dl=0

Navigation drawer asset:  https://www.dropbox.com/s/xxxsrcqikexxswg/nav_drawer.png?dl=0

Only render on AuthHome and ListAuthorization views.
Options:
  - "Home" -> AuthHome
 - "Authorizations" -> ListAuthorizations
 - "Log Out" -> (erase local account credentials and navigate to Login)

No icons need to be rendered for each option.

**Comment by jamslevy** [comment]
Completed
